name: Networking Library CI Pipelines

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v4

      - name: Run Lint Check
        run: ./gradlew lintDebug --stacktrace

      - name: Upload test Report
        uses: actions/upload-artifact@v4
        with:
          name: lint_report
          path: networking/build/reports/lint-results-debug.html

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Upload test Report
        uses: actions/upload-artifact@v4

        with:
          name: unit_test_report
          path: networking/build/reports/tests/testDebugUnitTest